### ISSUE TITLE
Progetto di Indirizzo!!!!!! {---}

### ISSUE THREAD

**Issue by spagnuolocarmine** [spagnuolocarmine/spagnuolocarmine.github.io#1]

**Comment by giusdam** [comment]
Sono Giuseppe D'Ambrosio e vorrei fare il progetto di indirizzo, in particolare sarei interessato al progetto riguardante Fly e Julia. Avendo avuto solo un'introduzione generale qualche informazione in più mi aiuterebbe a decidere meglio.

**Comment by MatDau** [comment]
_FLY_ è un Domain-Specific Language (DSL) per la progettazione di applicazioni di calcolo scientifico che sfrutta, in maniera semplice e trasparente, la potenza computazionale delle infrastrutture cloud. _FLY_ percepisce un'infrastruttura di cloud computing come un'architettura di calcolo parallela su cui è possibile eseguire alcune parti del suo flusso di esecuzione in parallelo.
Riassumendo, _FLY_ fornisce un supporto implicito al calcolo parallelo e distribuito, permettendo agli utenti di gestire ed elaborare i dati su un ambiente cloud senza lo sforzo di conoscere nel dettaglio le API fornite dai Cloud Vendor ma concentrandosi solamente sulla logica dell'applicazione che stanno implementando.

Lo sviluppo del DSL _FLY_ è iniziato sei/otto mesi fa e di conseguenza ci sono molti argomenti che possono essere trattati. Tali argomenti possono essere suddivisi in due filoni principali:

- Estendere il linguaggio, aggiungendo nuovi costrutti o funzionalità.

- Migliorare le funzionalità esistenti.

**Comment by alessant** [comment]
Per quanto riguarda Julia, il progetto è relativo al dominio degli ipergrafi. In particolare, stiamo lavorando ad una libreria scritta in Julia per modellare ipergrafi. Un _ipergrafo_ è una generalizzazione di un grafo dove un arco può connettere più di due vertici. Di conseguenza, gli ipergrafi sono in grado di modellare relazioni più complesse rispetto ai grafi e si prestano ad essere impiegati in numerose applicazioni.

Anche in questo caso, lo sviluppo è iniziato in tempi recentissimi e ci sono numerose strade che possono essere esplorate. Ad esempio è possibile:

- Estendere la libreria (un'idea potrebbe essere aggiungere una componente di visualizzazione)
- Utilizzare gli ipergrafi come strumento per modellare ed analizzare dati derivanti da social network

**Comment by spagnuolocarmine** [comment]
Altre informazioni generiche in merito i progetti di indirizzo sono disponibili in [questa presentazione](https://docs.google.com/presentation/d/1TL_xHuD2tjz3--lIYZjNqUCOoVloRxPXi01nVd_UKDI/edit?usp=sharing).
