### ISSUE TITLE
Sono riuscito a creare un cluster ma il test di un programma con MPI non viene eseguito

### ISSUE THREAD

**Issue by emaiannone** [spagnuolocarmine/spagnuolocarmine.github.io#2]
Ho creato un cluster di prova con 4 macchine. Su ciascuna ho eseguito passo passo il processo di setup, come riportato su GitHub. Quindi ho generato le chiavi ssh sul nodo master; le ho inserite nello script install.sh; ho copiato con scp lo script su tutti i nodi; ho eseguito lo script su ciascun nodo.
Andando sul nodo master, all'utente pcpc, ho lanciato: "mpicc -fopenmp test.c -o test.out", e viene creato il file test.out correttamente. Tuttavia al lancio con: "mpirun -np 2 ./test.out" ottengo il seguente errore:
"There are not enough slots available in the system to satisfy the 2 slots
that were requested by the application:
./test.out
Either request fewer slots for your application, or make more slots available
for use."

Deduco che il master non riesca a connettersi con i nodi slave. C'è un modo per essere sicuri che il master "veda" gli slave?

**Comment by spagnuolocarmine** [comment]
Salve deve copiare il file compilato o compilare su ogni nodo slave.

Inoltre deve essere sicuro che il file da eseguire si trova nello stesso path su tutti i nodi, in particolare partendo dalla /home/pcpc

**Comment by emaiannone** [comment]
Grazie, proverò il prima possibile.

**Comment by spagnuolocarmine** [comment]
Purtroppo è una nuova feature/bug della ultima versione di OpenMPI.
Come segnalato in quest thread di [stackoverflow](https://stackoverflow.com/questions/35704637/mpirun-not-enough-slots-available).

Per risolvere il problema dovete creare nel medesimo path dove avete compilato il vostro programma, un file chiamato machinefile, che contiene per ogni riga i nodi dove volete eseguire il programma.

```
localhost slots=1
172.16.3.1 slots=1
..
..
```

Inoltre bisogna utilizzare gli IP interni di AWS e specificare il numero di slots, che corrisponde al numero di VCPU, nel vostro caso di istanze t2.micro 1 slot.

Per avviare MPI specificando il hosts file:
```
mpirun --hostfile hostfile -np 2 a.out

```

Il numero di processi MPI (-np) deve essere uguale alla somma degli slot specificati nell'host file.

**Comment by emaiannone** [comment]
Ho riprovato da capo con due soli nodi. Nonostante abbia testato la correttezza dello scambio di chiavi facendo SSH dal nodo master verso lo slave, questo metodo del machinefile non mi va. Ho creato il seguente machinefile sull'utente pcpc del nodo master, nella stessa directory dell'eseguibile:
`localhost slots=1
172.31.93.32 slots=1`

Poi ho fatto `mpirun --hostfile machinefile -np 2 test.out`. L'esecuzione resta bloccata fino a che, con Ctrl+Z, termino l'esecuzione ed ottengo questo messaggio:

mpirun: Forwarding signal 20 to job
ORTE does not know how to route a message to the specified daemon
located on the indicated node:
  my node:   ip-172-31-90-40
  target node:  172.31.93.32
This is usually an internal programming error that should be
reported to the developers. In the meantime, a workaround may
be to set the MCA param routed=direct on the command line or
in your environment. We apologize for the problem.

Ho provato anche a creare il machinefile simmetrico sul nodo slave (sempre utente pcpc nella directory con l'eseguibile) ma nulla.

**Comment by emaiannone** [comment]
Ho ripetuto la procedura assicurandomi di fare correttamente lo scambio di chiavi e di usare un security group che accetta tutto in ingresso.
Dopo aver eseguito lo script sul nodo master e poi sul nodo slave sono riuscito a fare una connessione ssh dall'utente pcpc del nodo master verso l'utente pcpc del nodo slave. Pensavo di aver risolto. Compilo un programma di prova MPI e lo lancio con mpirun e vedo che c'è qualche problema: il master non trova altri slot. Mi assicuro che il machinefile sia a posto, e sembra di sì.
Decido di riprovare a fare la connessione ssh esattamente nello stesso modo di prima e mi viene restituito "Permission denied (publickey)". Provo anche a fare il reboot delle due istanze... nulla.

**Comment by Armando1514** [comment]
CONTROLLA I SEGUENTI STEP:
1) provando ad eseguire dal master ssh ip privato di slave x dà problemi? (se sì, copia bene id_rsa nello script).
2)Hai mandato a tutti gli slaves il file compilato del tuo test (il .out)?

**Comment by emaiannone** [comment]
Penso di aver copiato bene le chiavi nello script, anzi, l'ho fatto in due modi. Sia modificando lo script in locale e poi propagarlo a tutti i nodi via scp, sia passandoli prima via scp e modificandolo con vim in remoto. Nessuna differenza.
Per quanto riguarda il file post compilazione, io lancio mpicc su tutti i nodi, e non mi dà nessun problema sotto questo punto di vista.
A questo punto mi viene un dubbio: lo script, più o meno a metà, fa un'append delle chiavi sui file id_rsa, id_rsa.pub e authorized_keys, ma quando lo si esegue sul nodo master, vengono modificate le chiavi GIA' presenti. Può essere questa la causa dell'errore? Che mi si modificano le chiavi sul master?

**Comment by Armando1514** [comment]
Non devi lanciare mpicc su tutti i nodi, ma inviare tramite scp il file compilato dal master a tutti gli altri nodi. Try.

**Comment by emaiannone** [comment]
Il problema è che se non riesco a fare ssh dal master verso gli slave non riuscirò nemmeno a fare scp per passare loro il compilato

**Comment by Armando1514** [comment]
a me dava lo stesso problema con ssh, mi sono accorto che quando andavo a copiare id_rsa, non tenevo conto degli spazi, copia tutto, compreso i commenti e controlla.
