### ISSUE TITLE
Terminate your istance dod't waste your money!!!

### ISSUE THREAD

**Issue by giusdam** [spagnuolocarmine/spagnuolocarmine.github.io#3]
Quando finite di lavorare con le istante su AWS fate tasto destro sull'istanza - istance state - terminate per terminare l'istanza e non spendere soldi.

**Comment by emaiannone** [comment]
Terminare, tuttavia, fa perdere tutti i dati salvati nello storage, quindi se decide di terminare un intero cluster si è costretti a prepararlo da capo. Fare stop permette di mantenere i dati nello storage, ma comporta un dispendio di credito.

**Comment by spagnuolocarmine** [comment]
A questo [link](https://docs.aws.amazon.com/en_us/AWSEC2/latest/UserGuide/ec2-instance-lifecycle.html]) potete trovare tutto l'Instance Lifecycle con relative  Instance usage billing.

**Comment by giusdam** [comment]
Errata corrige, non fate terminate istance che equivale a cancellare l'intera istanza. Da quanto scritto nella documentazione Amazon basta stoppare l'istance e non verrà addebitato più alcun costo.

**Comment by spagnuolocarmine** [comment]
Ogni instance in stato stop consuma il costo pari a mantenere uno storage EBS di una certa dimensione. Dovete terminare le istanze per essere sicuri che non verrano addebitati costi involontari.
