### ISSUE TITLE
Errore Permesso Negato

### ISSUE THREAD

**Issue by ferr26** [spagnuolocarmine/spagnuolocarmine.github.io#4]
Salve, ho configurato la macchina virtuale. 
Ho effettuato lo scambio di chiavi, riesco a connettermi a pcpc e quando inserisco ssh localhost non mi da errori. 
Ma quando cerco di connettermi con ssh pcpc@(ip privato) mi da questo errore:
**pcpc@172.31.93.92: Permission denied (publickey).**

Quale potrebbe essere il problema?
Grazie a tutti e Buona Pasqua.

**Comment by spagnuolocarmine** [comment]
Deve verificare di aver correttamente generato e copiato le chiavi all'interno dello script install.sh.
Il contenuto delle chiavi pub/priv deve essere esattamente lo stesso nel file install.sh.

**Comment by ferr26** [comment]
![image](https://user-images.githubusercontent.com/49752047/56366812-40e25500-61f4-11e9-996b-d1e7ae06a2a8.png)

Ma nella terza chiave quale devo inserire? Sempre la chiave pubblica?

**Comment by francescomanzo** [comment]
Sì, devi metterci la chiave pubblica.

**Comment by ferr26** [comment]
Grazie, ho risolto.
